// lang-config.js
const translations = {
    en: {
        welcome: "Welcome to BotsQuick",
        byNkk: "By NKK Express",
        chooseLanguage: "Choose your language",
        bookBus: "Book a Bus",
        myTickets: "My Tickets",
        contactUs: "Contact Us",
        comingSoon: "(Coming Soon)",
        planTrip: "Plan Your Trip",
        selectRoute: "Select your route and travel date",
        from: "From",
        to: "To",
        selectDeparture: "Select departure",
        selectDestination: "Select destination",
        travelDate: "Travel Date",
        preferredTime: "Preferred Time",
        selectTime: "Select time",
        chooseSeats: "Choose Seats",
        selectSeat: "Select Your Seat",
        choosePreferred: "Choose your preferred seat",
        tripSummary: "Trip Summary",
        route: "Route",
        date: "Date",
        time: "Time",
        busLayout: "Bus Layout",
        available: "Available",
        selected: "Selected",
        occupied: "Occupied",
        selectedSeat: "Selected Seat",
        price: "Price",
        continuePayment: "Continue to Payment",
        back: "Back",
        completeBooking: "Complete Your Booking",
        choosePayment: "Choose payment method",
        yourInfo: "Your Information",
        fullName: "Full Name",
        enterName: "Enter your full name",
        phoneNumber: "Phone Number",
        enterPhone: "Enter your phone number",
        email: "Email (Optional)",
        enterEmail: "Enter your email",
        paymentMethod: "Payment Method",
        orangeMoney: "Orange Money",
        card: "Credit/Debit Card",
        cash: "Pay Cash at Terminal",
        cardNumber: "Card Number",
        expiryDate: "Expiry Date",
        cvv: "CVV",
        confirmPayment: "Confirm Payment",
        bookingConfirmed: "Booking Confirmed!",
        yourTripReserved: "Your trip is reserved",
        thankYou: "Thank You for Choosing NKK Express",
        bookingDetails: "Booking Details",
        referenceNumber: "Reference Number",
        passenger: "Passenger",
        totalPaid: "Total Paid",
        importantInfo: "Important Information",
        arriveEarly: "Please arrive at the terminal 30 minutes before departure",
        bringId: "Bring your ID and this booking reference",
        cashPayment: "For cash payments, pay at the terminal before boarding",
        printTicket: "Print Ticket",
        bookAnother: "Book Another Trip",
        driver: "Driver",
        ussdPrompt: "You will receive a USSD prompt to confirm payment",
        cashInstructions: "Bring your booking reference to any NKK Express terminal to pay in cash"
    },
    tn: {
        welcome: "Amogela go BotsQuick",
        byNkk: "Ke NKK Express",
        chooseLanguage: "Kgethile puo ya gago",
        bookBus: "Buka Bese",
        myTickets: "Dikitikhete tsa me",
        contactUs: "Ikopanye le rona",
        comingSoon: "(E tla kgantele)",
        planTrip: "Rera Leeto la gago",
        selectRoute: "Kgetha tsela le letsatsi la tsela",
        from: "Go tswa",
        to: "Go ya",
        selectDeparture: "Kgetha letlolego",
        selectDestination: "Kgetha lebaka",
        travelDate: "Letsatsi la tsela",
        preferredTime: "Nako e o e ratang",
        selectTime: "Kgetha nako",
        chooseSeats: "Kgetha Ditsesi",
        selectSeat: "Kgetha Setsi sa gago",
        choosePreferred: "Kgetha setsi se o se ratang",
        tripSummary: "Kakaretso ya leeto",
        route: "Tsela",
        date: "Letsatsi",
        time: "Nako",
        busLayout: "Popego ya bese",
        available: "E e leng gona",
        selected: "E e kgethilweng",
        occupied: "E e tsereng",
        selectedSeat: "Setsi se se kgethilweng",
        price: "Mokitlana",
        continuePayment: "Tswelela go duela",
        back: "Ko Morago",
        completeBooking: "Feleletsa go buka",
        choosePayment: "Kgetha mokgwa wa tefelo",
        yourInfo: "Tshedimosotho ya gago",
        fullName: "Maina a a feletseng",
        enterName: "Kwala maina a gago a a feletseng",
        phoneNumber: "Nomoro ya mogala",
        enterPhone: "Kwala nomoro ya gago ya mogala",
        email: "Email (Ka boithaopo)",
        enterEmail: "Kwala email ya gago",
        paymentMethod: "Mokgwa wa tefelo",
        orangeMoney: "Orange Money",
        card: "Karatšhe ya go duela",
        cash: "Duela ka madi a sephatlo",
        cardNumber: "Nomoro ya karatšhe",
        expiryDate: "Letsatsi la go fela",
        cvv: "CVV",
        confirmPayment: "Tlhomamisa tefelo",
        bookingConfirmed: "Go buka go tlhomamisitswe!",
        yourTripReserved: "Leeto la gago le beilwe",
        thankYou: "Re a leboga go kgetha NKK Express",
        bookingDetails: "Ditlhakore tsa go buka",
        referenceNumber: "Nomoro ya tesupo",
        passenger: "Molebeli",
        totalPaid: "Kakaretso e e dueditsweng",
        importantInfo: "Tshedimosotho e e botlhokwa",
        arriveEarly: "Re a go kgothaletsa go fihla tereminal metsotso e le 30 pele ga go simolola",
        bringId: "Tlisana le ID le tesupo ena ya go buka",
        cashPayment: "Go duela ka madi a sephatlo, duela kwa tereminal pele ga go namela",
        printTicket: "Gatisa tikiti",
        bookAnother: "Buka leeto le lengwe",
        driver: "Mokganedi",
        ussdPrompt: "O tla amogela USSD go tlhomamisa tefelo",
        cashInstructions: "Tlisana le tesupo ya gago ya go buka kwa tereminal ya NKK Express go duela ka madi a sephatlo"
    }
};

function applyTranslations(lang) {
    const elements = document.querySelectorAll('[data-translate]');
    elements.forEach(element => {
        const key = element.getAttribute('data-translate');
        if (translations[lang] && translations[lang][key]) {
            if (element.tagName === 'INPUT' || element.tagName === 'SELECT') {
                element.placeholder = translations[lang][key];
            } else if (element.hasAttribute('title')) {
                element.title = translations[lang][key];
            } else {
                element.textContent = translations[lang][key];
            }
        }
    });
}

function getCurrentLanguage() {
    return localStorage.getItem('userLanguage') || 'en';
}